# Generated by Django 5.1.5 on 2025-02-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('visibility', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('wind_gust_dir', models.CharField(max_length=50)),
                ('wind_gust_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('temp', models.FloatField()),
                ('rain_tomorrow', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('predicted_temp', models.FloatField()),
                ('predicted_humidity', models.FloatField()),
                ('predicted_rain', models.IntegerField()),
                ('predicted_times', models.JSONField()),
                ('predicted_temps', models.JSONField()),
                ('predicted_hums', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
